// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookmarks.sql

package sqlccommunity

import (
	"context"

	"github.com/google/uuid"
)

const countBookmarksByUser = `-- name: CountBookmarksByUser :one
SELECT COUNT(*)::int FROM bookmarks WHERE user_id = $1
`

func (q *Queries) CountBookmarksByUser(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countBookmarksByUser, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (id, user_id, word_id, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, user_id, word_id, created_at
`

type CreateBookmarkParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	WordID uuid.UUID `db:"word_id" json:"word_id"`
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, createBookmark, arg.ID, arg.UserID, arg.WordID)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WordID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks WHERE user_id = $1 AND word_id = $2
`

type DeleteBookmarkParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	WordID uuid.UUID `db:"word_id" json:"word_id"`
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookmark, arg.UserID, arg.WordID)
	return err
}

const getBookmarkByUserAndWord = `-- name: GetBookmarkByUserAndWord :one
SELECT id, user_id, word_id, created_at FROM bookmarks WHERE user_id = $1 AND word_id = $2 LIMIT 1
`

type GetBookmarkByUserAndWordParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	WordID uuid.UUID `db:"word_id" json:"word_id"`
}

func (q *Queries) GetBookmarkByUserAndWord(ctx context.Context, arg GetBookmarkByUserAndWordParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, getBookmarkByUserAndWord, arg.UserID, arg.WordID)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WordID,
		&i.CreatedAt,
	)
	return i, err
}

const listBookmarksByUser = `-- name: ListBookmarksByUser :many
SELECT id, user_id, word_id, created_at FROM bookmarks
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBookmarksByUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListBookmarksByUser(ctx context.Context, arg ListBookmarksByUserParams) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, listBookmarksByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WordID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
