// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package sqlccommunity

import (
	"context"

	"github.com/google/uuid"
)

const countCommentsByTarget = `-- name: CountCommentsByTarget :one
SELECT COUNT(*)::int FROM comments WHERE target_type = $1 AND target_id = $2
`

type CountCommentsByTargetParams struct {
	TargetType CommentTargetType `db:"target_type" json:"target_type"`
	TargetID   uuid.UUID         `db:"target_id" json:"target_id"`
}

func (q *Queries) CountCommentsByTarget(ctx context.Context, arg CountCommentsByTargetParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countCommentsByTarget, arg.TargetType, arg.TargetID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (id, user_id, target_type, target_id, body, is_flagged, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, FALSE, NOW(), NOW())
RETURNING id, user_id, target_type, target_id, body, is_flagged, created_at, updated_at
`

type CreateCommentParams struct {
	ID         uuid.UUID         `db:"id" json:"id"`
	UserID     uuid.UUID         `db:"user_id" json:"user_id"`
	TargetType CommentTargetType `db:"target_type" json:"target_type"`
	TargetID   uuid.UUID         `db:"target_id" json:"target_id"`
	Body       string            `db:"body" json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.ID,
		arg.UserID,
		arg.TargetType,
		arg.TargetID,
		arg.Body,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetType,
		&i.TargetID,
		&i.Body,
		&i.IsFlagged,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const flagComment = `-- name: FlagComment :one
UPDATE comments
SET is_flagged = TRUE,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, target_type, target_id, body, is_flagged, created_at, updated_at
`

func (q *Queries) FlagComment(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRowContext(ctx, flagComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetType,
		&i.TargetID,
		&i.Body,
		&i.IsFlagged,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, user_id, target_type, target_id, body, is_flagged, created_at, updated_at FROM comments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetType,
		&i.TargetID,
		&i.Body,
		&i.IsFlagged,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommentsByTarget = `-- name: ListCommentsByTarget :many
SELECT id, user_id, target_type, target_id, body, is_flagged, created_at, updated_at FROM comments
WHERE target_type = $1 AND target_id = $2
ORDER BY created_at ASC
LIMIT $3 OFFSET $4
`

type ListCommentsByTargetParams struct {
	TargetType CommentTargetType `db:"target_type" json:"target_type"`
	TargetID   uuid.UUID         `db:"target_id" json:"target_id"`
	Limit      int32             `db:"limit" json:"limit"`
	Offset     int32             `db:"offset" json:"offset"`
}

func (q *Queries) ListCommentsByTarget(ctx context.Context, arg ListCommentsByTargetParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByTarget,
		arg.TargetType,
		arg.TargetID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TargetType,
			&i.TargetID,
			&i.Body,
			&i.IsFlagged,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET body       = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, target_type, target_id, body, is_flagged, created_at, updated_at
`

type UpdateCommentParams struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Body string    `db:"body" json:"body"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, updateComment, arg.ID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetType,
		&i.TargetID,
		&i.Body,
		&i.IsFlagged,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
