// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contributions.sql

package sqlccommunity

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const countAllContributions = `-- name: CountAllContributions :one
SELECT COUNT(*)::int FROM contributions
WHERE ($1::text = '' OR status::text = $1::text)
  AND ($2::text = '' OR type::text = $2::text)
`

type CountAllContributionsParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
}

func (q *Queries) CountAllContributions(ctx context.Context, arg CountAllContributionsParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countAllContributions, arg.Column1, arg.Column2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countContributionsByContributor = `-- name: CountContributionsByContributor :one
SELECT COUNT(*)::int FROM contributions
WHERE contributor_id = $1
  AND ($2::text = '' OR status::text = $2::text)
  AND ($3::text = '' OR type::text = $3::text)
`

type CountContributionsByContributorParams struct {
	ContributorID uuid.UUID `db:"contributor_id" json:"contributor_id"`
	Column2       string    `db:"column_2" json:"column_2"`
	Column3       string    `db:"column_3" json:"column_3"`
}

func (q *Queries) CountContributionsByContributor(ctx context.Context, arg CountContributionsByContributorParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countContributionsByContributor, arg.ContributorID, arg.Column2, arg.Column3)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createContribution = `-- name: CreateContribution :one
INSERT INTO contributions (id, type, contributor_id, target_word_id, payload, status, submitted_at)
VALUES ($1, $2, $3, $4, $5, 'pending', NOW())
RETURNING id, type, contributor_id, target_word_id, payload, status, reviewer_id, reviewer_note, submitted_at, reviewed_at
`

type CreateContributionParams struct {
	ID            uuid.UUID        `db:"id" json:"id"`
	Type          ContributionType `db:"type" json:"type"`
	ContributorID uuid.UUID        `db:"contributor_id" json:"contributor_id"`
	TargetWordID  uuid.NullUUID    `db:"target_word_id" json:"target_word_id"`
	Payload       json.RawMessage  `db:"payload" json:"payload"`
}

func (q *Queries) CreateContribution(ctx context.Context, arg CreateContributionParams) (Contribution, error) {
	row := q.db.QueryRowContext(ctx, createContribution,
		arg.ID,
		arg.Type,
		arg.ContributorID,
		arg.TargetWordID,
		arg.Payload,
	)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ContributorID,
		&i.TargetWordID,
		&i.Payload,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewerNote,
		&i.SubmittedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const getContributionByID = `-- name: GetContributionByID :one
SELECT id, type, contributor_id, target_word_id, payload, status, reviewer_id, reviewer_note, submitted_at, reviewed_at FROM contributions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetContributionByID(ctx context.Context, id uuid.UUID) (Contribution, error) {
	row := q.db.QueryRowContext(ctx, getContributionByID, id)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ContributorID,
		&i.TargetWordID,
		&i.Payload,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewerNote,
		&i.SubmittedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const listAllContributions = `-- name: ListAllContributions :many
SELECT id, type, contributor_id, target_word_id, payload, status, reviewer_id, reviewer_note, submitted_at, reviewed_at FROM contributions
WHERE ($1::text = '' OR status::text = $1::text)
  AND ($2::text = '' OR type::text = $2::text)
ORDER BY submitted_at DESC
LIMIT $3 OFFSET $4
`

type ListAllContributionsParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListAllContributions(ctx context.Context, arg ListAllContributionsParams) ([]Contribution, error) {
	rows, err := q.db.QueryContext(ctx, listAllContributions,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contribution{}
	for rows.Next() {
		var i Contribution
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ContributorID,
			&i.TargetWordID,
			&i.Payload,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewerNote,
			&i.SubmittedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContributionsByContributor = `-- name: ListContributionsByContributor :many
SELECT id, type, contributor_id, target_word_id, payload, status, reviewer_id, reviewer_note, submitted_at, reviewed_at FROM contributions
WHERE contributor_id = $1
  AND ($2::text = '' OR status::text = $2::text)
  AND ($3::text = '' OR type::text = $3::text)
ORDER BY submitted_at DESC
LIMIT $4 OFFSET $5
`

type ListContributionsByContributorParams struct {
	ContributorID uuid.UUID `db:"contributor_id" json:"contributor_id"`
	Column2       string    `db:"column_2" json:"column_2"`
	Column3       string    `db:"column_3" json:"column_3"`
	Limit         int32     `db:"limit" json:"limit"`
	Offset        int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListContributionsByContributor(ctx context.Context, arg ListContributionsByContributorParams) ([]Contribution, error) {
	rows, err := q.db.QueryContext(ctx, listContributionsByContributor,
		arg.ContributorID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contribution{}
	for rows.Next() {
		var i Contribution
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ContributorID,
			&i.TargetWordID,
			&i.Payload,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewerNote,
			&i.SubmittedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContribution = `-- name: UpdateContribution :one
UPDATE contributions
SET status        = $2,
    reviewer_id   = $3,
    reviewer_note = $4,
    reviewed_at   = $5
WHERE id = $1
RETURNING id, type, contributor_id, target_word_id, payload, status, reviewer_id, reviewer_note, submitted_at, reviewed_at
`

type UpdateContributionParams struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Status       ContributionStatus `db:"status" json:"status"`
	ReviewerID   uuid.NullUUID      `db:"reviewer_id" json:"reviewer_id"`
	ReviewerNote sql.NullString     `db:"reviewer_note" json:"reviewer_note"`
	ReviewedAt   sql.NullTime       `db:"reviewed_at" json:"reviewed_at"`
}

func (q *Queries) UpdateContribution(ctx context.Context, arg UpdateContributionParams) (Contribution, error) {
	row := q.db.QueryRowContext(ctx, updateContribution,
		arg.ID,
		arg.Status,
		arg.ReviewerID,
		arg.ReviewerNote,
		arg.ReviewedAt,
	)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ContributorID,
		&i.TargetWordID,
		&i.Payload,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewerNote,
		&i.SubmittedAt,
		&i.ReviewedAt,
	)
	return i, err
}
