// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: votes.sql

package sqlccommunity

import (
	"context"

	"github.com/google/uuid"
)

const deleteVote = `-- name: DeleteVote :exec
DELETE FROM votes
WHERE user_id = $1 AND target_type = $2 AND target_id = $3
`

type DeleteVoteParams struct {
	UserID     uuid.UUID      `db:"user_id" json:"user_id"`
	TargetType VoteTargetType `db:"target_type" json:"target_type"`
	TargetID   uuid.UUID      `db:"target_id" json:"target_id"`
}

func (q *Queries) DeleteVote(ctx context.Context, arg DeleteVoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteVote, arg.UserID, arg.TargetType, arg.TargetID)
	return err
}

const getVoteByUserAndTarget = `-- name: GetVoteByUserAndTarget :one
SELECT id, user_id, target_type, target_id, value, created_at FROM votes
WHERE user_id = $1 AND target_type = $2 AND target_id = $3
LIMIT 1
`

type GetVoteByUserAndTargetParams struct {
	UserID     uuid.UUID      `db:"user_id" json:"user_id"`
	TargetType VoteTargetType `db:"target_type" json:"target_type"`
	TargetID   uuid.UUID      `db:"target_id" json:"target_id"`
}

func (q *Queries) GetVoteByUserAndTarget(ctx context.Context, arg GetVoteByUserAndTargetParams) (Vote, error) {
	row := q.db.QueryRowContext(ctx, getVoteByUserAndTarget, arg.UserID, arg.TargetType, arg.TargetID)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetType,
		&i.TargetID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const upsertVote = `-- name: UpsertVote :one
INSERT INTO votes (id, user_id, target_type, target_id, value, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (user_id, target_type, target_id) DO UPDATE
    SET value = EXCLUDED.value
RETURNING id, user_id, target_type, target_id, value, created_at
`

type UpsertVoteParams struct {
	ID         uuid.UUID      `db:"id" json:"id"`
	UserID     uuid.UUID      `db:"user_id" json:"user_id"`
	TargetType VoteTargetType `db:"target_type" json:"target_type"`
	TargetID   uuid.UUID      `db:"target_id" json:"target_id"`
	Value      VoteValue      `db:"value" json:"value"`
}

func (q *Queries) UpsertVote(ctx context.Context, arg UpsertVoteParams) (Vote, error) {
	row := q.db.QueryRowContext(ctx, upsertVote,
		arg.ID,
		arg.UserID,
		arg.TargetType,
		arg.TargetID,
		arg.Value,
	)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetType,
		&i.TargetID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}
