version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gosimple
    - unused
    - revive
    - misspell
    - gocritic
    - exhaustive
  settings:
    gocritic:
      disabled-checks:
        - commentedOutCode

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/iqbaleff214/kamus-banjar-api-2
