// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_requests.sql

package sqlcai

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countAIRequestsByWord = `-- name: CountAIRequestsByWord :one
SELECT COUNT(*)::int FROM ai_requests WHERE target_word_id = $1
`

func (q *Queries) CountAIRequestsByWord(ctx context.Context, targetWordID uuid.NullUUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countAIRequestsByWord, targetWordID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countAIRequestsPendingReview = `-- name: CountAIRequestsPendingReview :one
SELECT COUNT(*)::int FROM ai_requests
WHERE status = 'completed' AND review_status = 'unreviewed'
`

func (q *Queries) CountAIRequestsPendingReview(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, countAIRequestsPendingReview)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createAIRequest = `-- name: CreateAIRequest :exec
INSERT INTO ai_requests (
    id, type, target_word_id, target_contribution_id, requested_by,
    model, prompt, response, parsed_output, status, review_status,
    reviewed_by, reviewed_at, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateAIRequestParams struct {
	ID                   uuid.UUID             `db:"id" json:"id"`
	Type                 string                `db:"type" json:"type"`
	TargetWordID         uuid.NullUUID         `db:"target_word_id" json:"target_word_id"`
	TargetContributionID uuid.NullUUID         `db:"target_contribution_id" json:"target_contribution_id"`
	RequestedBy          uuid.UUID             `db:"requested_by" json:"requested_by"`
	Model                string                `db:"model" json:"model"`
	Prompt               string                `db:"prompt" json:"prompt"`
	Response             pqtype.NullRawMessage `db:"response" json:"response"`
	ParsedOutput         pqtype.NullRawMessage `db:"parsed_output" json:"parsed_output"`
	Status               string                `db:"status" json:"status"`
	ReviewStatus         string                `db:"review_status" json:"review_status"`
	ReviewedBy           uuid.NullUUID         `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt           sql.NullTime          `db:"reviewed_at" json:"reviewed_at"`
	CreatedAt            time.Time             `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateAIRequest(ctx context.Context, arg CreateAIRequestParams) error {
	_, err := q.db.ExecContext(ctx, createAIRequest,
		arg.ID,
		arg.Type,
		arg.TargetWordID,
		arg.TargetContributionID,
		arg.RequestedBy,
		arg.Model,
		arg.Prompt,
		arg.Response,
		arg.ParsedOutput,
		arg.Status,
		arg.ReviewStatus,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.CreatedAt,
	)
	return err
}

const getAIRequestByID = `-- name: GetAIRequestByID :one
SELECT id, type, target_word_id, target_contribution_id, requested_by,
       model, prompt, response, parsed_output, status, review_status,
       reviewed_by, reviewed_at, created_at
FROM ai_requests
WHERE id = $1
`

func (q *Queries) GetAIRequestByID(ctx context.Context, id uuid.UUID) (AiRequest, error) {
	row := q.db.QueryRowContext(ctx, getAIRequestByID, id)
	var i AiRequest
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TargetWordID,
		&i.TargetContributionID,
		&i.RequestedBy,
		&i.Model,
		&i.Prompt,
		&i.Response,
		&i.ParsedOutput,
		&i.Status,
		&i.ReviewStatus,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAIRequestsByWord = `-- name: ListAIRequestsByWord :many
SELECT id, type, target_word_id, target_contribution_id, requested_by,
       model, prompt, response, parsed_output, status, review_status,
       reviewed_by, reviewed_at, created_at
FROM ai_requests
WHERE target_word_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAIRequestsByWordParams struct {
	TargetWordID uuid.NullUUID `db:"target_word_id" json:"target_word_id"`
	Limit        int32         `db:"limit" json:"limit"`
	Offset       int32         `db:"offset" json:"offset"`
}

func (q *Queries) ListAIRequestsByWord(ctx context.Context, arg ListAIRequestsByWordParams) ([]AiRequest, error) {
	rows, err := q.db.QueryContext(ctx, listAIRequestsByWord, arg.TargetWordID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiRequest{}
	for rows.Next() {
		var i AiRequest
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TargetWordID,
			&i.TargetContributionID,
			&i.RequestedBy,
			&i.Model,
			&i.Prompt,
			&i.Response,
			&i.ParsedOutput,
			&i.Status,
			&i.ReviewStatus,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIRequestsPendingReview = `-- name: ListAIRequestsPendingReview :many
SELECT id, type, target_word_id, target_contribution_id, requested_by,
       model, prompt, response, parsed_output, status, review_status,
       reviewed_by, reviewed_at, created_at
FROM ai_requests
WHERE status = 'completed' AND review_status = 'unreviewed'
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListAIRequestsPendingReviewParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListAIRequestsPendingReview(ctx context.Context, arg ListAIRequestsPendingReviewParams) ([]AiRequest, error) {
	rows, err := q.db.QueryContext(ctx, listAIRequestsPendingReview, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiRequest{}
	for rows.Next() {
		var i AiRequest
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TargetWordID,
			&i.TargetContributionID,
			&i.RequestedBy,
			&i.Model,
			&i.Prompt,
			&i.Response,
			&i.ParsedOutput,
			&i.Status,
			&i.ReviewStatus,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAIRequest = `-- name: UpdateAIRequest :exec
UPDATE ai_requests
SET response       = $2,
    parsed_output  = $3,
    status         = $4,
    review_status  = $5,
    reviewed_by    = $6,
    reviewed_at    = $7
WHERE id = $1
`

type UpdateAIRequestParams struct {
	ID           uuid.UUID             `db:"id" json:"id"`
	Response     pqtype.NullRawMessage `db:"response" json:"response"`
	ParsedOutput pqtype.NullRawMessage `db:"parsed_output" json:"parsed_output"`
	Status       string                `db:"status" json:"status"`
	ReviewStatus string                `db:"review_status" json:"review_status"`
	ReviewedBy   uuid.NullUUID         `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt   sql.NullTime          `db:"reviewed_at" json:"reviewed_at"`
}

func (q *Queries) UpdateAIRequest(ctx context.Context, arg UpdateAIRequestParams) error {
	_, err := q.db.ExecContext(ctx, updateAIRequest,
		arg.ID,
		arg.Response,
		arg.ParsedOutput,
		arg.Status,
		arg.ReviewStatus,
		arg.ReviewedBy,
		arg.ReviewedAt,
	)
	return err
}
