// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package sqlcmoderation

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (id, actor_id, action, target_type, target_id, metadata, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAuditLogParams struct {
	ID         uuid.UUID             `db:"id" json:"id"`
	ActorID    uuid.UUID             `db:"actor_id" json:"actor_id"`
	Action     string                `db:"action" json:"action"`
	TargetType string                `db:"target_type" json:"target_type"`
	TargetID   uuid.UUID             `db:"target_id" json:"target_id"`
	Metadata   pqtype.NullRawMessage `db:"metadata" json:"metadata"`
	CreatedAt  time.Time             `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.ID,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const getModerationStats = `-- name: GetModerationStats :one
SELECT
    (SELECT COUNT(*) FROM contributions WHERE status = 'pending')::int                                                          AS pending_contributions,
    (SELECT COUNT(*) FROM comments WHERE is_flagged = true)::int                                                                AS flagged_comments,
    (SELECT COUNT(*) FROM contributions WHERE status = 'approved' AND reviewed_at >= NOW() - INTERVAL '7 days')::int           AS approved_this_week,
    (SELECT COUNT(*) FROM contributions WHERE status = 'rejected' AND reviewed_at >= NOW() - INTERVAL '7 days')::int           AS rejected_this_week
`

type GetModerationStatsRow struct {
	PendingContributions int32 `db:"pending_contributions" json:"pending_contributions"`
	FlaggedComments      int32 `db:"flagged_comments" json:"flagged_comments"`
	ApprovedThisWeek     int32 `db:"approved_this_week" json:"approved_this_week"`
	RejectedThisWeek     int32 `db:"rejected_this_week" json:"rejected_this_week"`
}

func (q *Queries) GetModerationStats(ctx context.Context) (GetModerationStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getModerationStats)
	var i GetModerationStatsRow
	err := row.Scan(
		&i.PendingContributions,
		&i.FlaggedComments,
		&i.ApprovedThisWeek,
		&i.RejectedThisWeek,
	)
	return i, err
}
