// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcmoderation

import (
	"context"
)

const countUsersAdmin = `-- name: CountUsersAdmin :one
SELECT COUNT(*)::int FROM users
WHERE
    ($1::text = '' OR role = $1::text)
    AND ($2::text = '' OR is_active::text = $2::text)
    AND ($3::text = '' OR name ILIKE '%' || $3 || '%' OR email ILIKE '%' || $3 || '%')
`

type CountUsersAdminParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
	Column3 string `db:"column_3" json:"column_3"`
}

func (q *Queries) CountUsersAdmin(ctx context.Context, arg CountUsersAdminParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countUsersAdmin, arg.Column1, arg.Column2, arg.Column3)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT id, name, email, password_hash, role, is_active, email_verified_at, created_at, updated_at
FROM users
WHERE
    ($1::text = '' OR role = $1::text)
    AND ($2::text = '' OR is_active::text = $2::text)
    AND ($3::text = '' OR name ILIKE '%' || $3 || '%' OR email ILIKE '%' || $3 || '%')
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListUsersAdminParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
	Column3 string `db:"column_3" json:"column_3"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersAdmin,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
