// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: definitions.sql

package sqlcdictionary

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDefinition = `-- name: CreateDefinition :one
INSERT INTO definitions (id, word_id, meaning, sort_order, source, upvotes, downvotes, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, word_id, meaning, sort_order, source, upvotes, downvotes, created_at, updated_at
`

type CreateDefinitionParams struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	WordID    uuid.UUID  `db:"word_id" json:"word_id"`
	Meaning   string     `db:"meaning" json:"meaning"`
	SortOrder int16      `db:"sort_order" json:"sort_order"`
	Source    WordSource `db:"source" json:"source"`
	Upvotes   int32      `db:"upvotes" json:"upvotes"`
	Downvotes int32      `db:"downvotes" json:"downvotes"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt time.Time  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateDefinition(ctx context.Context, arg CreateDefinitionParams) (Definition, error) {
	row := q.db.QueryRowContext(ctx, createDefinition,
		arg.ID,
		arg.WordID,
		arg.Meaning,
		arg.SortOrder,
		arg.Source,
		arg.Upvotes,
		arg.Downvotes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Definition
	err := row.Scan(
		&i.ID,
		&i.WordID,
		&i.Meaning,
		&i.SortOrder,
		&i.Source,
		&i.Upvotes,
		&i.Downvotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDefinitionsByWordID = `-- name: DeleteDefinitionsByWordID :exec
DELETE FROM definitions WHERE word_id = $1
`

func (q *Queries) DeleteDefinitionsByWordID(ctx context.Context, wordID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDefinitionsByWordID, wordID)
	return err
}

const getDefinitionByID = `-- name: GetDefinitionByID :one
SELECT id, word_id, meaning, sort_order, source, upvotes, downvotes, created_at, updated_at FROM definitions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDefinitionByID(ctx context.Context, id uuid.UUID) (Definition, error) {
	row := q.db.QueryRowContext(ctx, getDefinitionByID, id)
	var i Definition
	err := row.Scan(
		&i.ID,
		&i.WordID,
		&i.Meaning,
		&i.SortOrder,
		&i.Source,
		&i.Upvotes,
		&i.Downvotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefinitionsByWordID = `-- name: GetDefinitionsByWordID :many
SELECT id, word_id, meaning, sort_order, source, upvotes, downvotes, created_at, updated_at FROM definitions
WHERE word_id = $1
ORDER BY sort_order ASC, (upvotes - downvotes) DESC
`

func (q *Queries) GetDefinitionsByWordID(ctx context.Context, wordID uuid.UUID) ([]Definition, error) {
	rows, err := q.db.QueryContext(ctx, getDefinitionsByWordID, wordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Definition{}
	for rows.Next() {
		var i Definition
		if err := rows.Scan(
			&i.ID,
			&i.WordID,
			&i.Meaning,
			&i.SortOrder,
			&i.Source,
			&i.Upvotes,
			&i.Downvotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDefinition = `-- name: UpsertDefinition :one
INSERT INTO definitions (id, word_id, meaning, sort_order, source, upvotes, downvotes, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE
SET meaning    = EXCLUDED.meaning,
    sort_order = EXCLUDED.sort_order,
    updated_at = EXCLUDED.updated_at
RETURNING id, word_id, meaning, sort_order, source, upvotes, downvotes, created_at, updated_at
`

type UpsertDefinitionParams struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	WordID    uuid.UUID  `db:"word_id" json:"word_id"`
	Meaning   string     `db:"meaning" json:"meaning"`
	SortOrder int16      `db:"sort_order" json:"sort_order"`
	Source    WordSource `db:"source" json:"source"`
	Upvotes   int32      `db:"upvotes" json:"upvotes"`
	Downvotes int32      `db:"downvotes" json:"downvotes"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt time.Time  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertDefinition(ctx context.Context, arg UpsertDefinitionParams) (Definition, error) {
	row := q.db.QueryRowContext(ctx, upsertDefinition,
		arg.ID,
		arg.WordID,
		arg.Meaning,
		arg.SortOrder,
		arg.Source,
		arg.Upvotes,
		arg.Downvotes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Definition
	err := row.Scan(
		&i.ID,
		&i.WordID,
		&i.Meaning,
		&i.SortOrder,
		&i.Source,
		&i.Upvotes,
		&i.Downvotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
