// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: examples.sql

package sqlcdictionary

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createExample = `-- name: CreateExample :one
INSERT INTO examples (id, word_id, banjar_sentence, indonesian_translation, source, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, word_id, banjar_sentence, indonesian_translation, source, created_at, updated_at
`

type CreateExampleParams struct {
	ID                    uuid.UUID  `db:"id" json:"id"`
	WordID                uuid.UUID  `db:"word_id" json:"word_id"`
	BanjarSentence        string     `db:"banjar_sentence" json:"banjar_sentence"`
	IndonesianTranslation string     `db:"indonesian_translation" json:"indonesian_translation"`
	Source                WordSource `db:"source" json:"source"`
	CreatedAt             time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateExample(ctx context.Context, arg CreateExampleParams) (Example, error) {
	row := q.db.QueryRowContext(ctx, createExample,
		arg.ID,
		arg.WordID,
		arg.BanjarSentence,
		arg.IndonesianTranslation,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.WordID,
		&i.BanjarSentence,
		&i.IndonesianTranslation,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExamplesByWordID = `-- name: DeleteExamplesByWordID :exec
DELETE FROM examples WHERE word_id = $1
`

func (q *Queries) DeleteExamplesByWordID(ctx context.Context, wordID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteExamplesByWordID, wordID)
	return err
}

const getExamplesByWordID = `-- name: GetExamplesByWordID :many
SELECT id, word_id, banjar_sentence, indonesian_translation, source, created_at, updated_at FROM examples
WHERE word_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetExamplesByWordID(ctx context.Context, wordID uuid.UUID) ([]Example, error) {
	rows, err := q.db.QueryContext(ctx, getExamplesByWordID, wordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Example{}
	for rows.Next() {
		var i Example
		if err := rows.Scan(
			&i.ID,
			&i.WordID,
			&i.BanjarSentence,
			&i.IndonesianTranslation,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExample = `-- name: UpsertExample :one
INSERT INTO examples (id, word_id, banjar_sentence, indonesian_translation, source, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE
SET banjar_sentence        = EXCLUDED.banjar_sentence,
    indonesian_translation = EXCLUDED.indonesian_translation,
    updated_at             = EXCLUDED.updated_at
RETURNING id, word_id, banjar_sentence, indonesian_translation, source, created_at, updated_at
`

type UpsertExampleParams struct {
	ID                    uuid.UUID  `db:"id" json:"id"`
	WordID                uuid.UUID  `db:"word_id" json:"word_id"`
	BanjarSentence        string     `db:"banjar_sentence" json:"banjar_sentence"`
	IndonesianTranslation string     `db:"indonesian_translation" json:"indonesian_translation"`
	Source                WordSource `db:"source" json:"source"`
	CreatedAt             time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertExample(ctx context.Context, arg UpsertExampleParams) (Example, error) {
	row := q.db.QueryRowContext(ctx, upsertExample,
		arg.ID,
		arg.WordID,
		arg.BanjarSentence,
		arg.IndonesianTranslation,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.WordID,
		&i.BanjarSentence,
		&i.IndonesianTranslation,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
