// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdictionary

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Dialect string

const (
	DialectHulu Dialect = "hulu"
)

func (e *Dialect) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Dialect(s)
	case string:
		*e = Dialect(s)
	default:
		return fmt.Errorf("unsupported scan type for Dialect: %T", src)
	}
	return nil
}

type NullDialect struct {
	Dialect Dialect `json:"dialect"`
	Valid   bool    `json:"valid"` // Valid is true if Dialect is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDialect) Scan(value interface{}) error {
	if value == nil {
		ns.Dialect, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Dialect.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDialect) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Dialect), nil
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type WordClass string

const (
	WordClassN   WordClass = "n"
	WordClassV   WordClass = "v"
	WordClassA   WordClass = "a"
	WordClassAdv WordClass = "adv"
	WordClassP   WordClass = "p"
	WordClassPb  WordClass = "pb"
	WordClassKi  WordClass = "ki"
)

func (e *WordClass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WordClass(s)
	case string:
		*e = WordClass(s)
	default:
		return fmt.Errorf("unsupported scan type for WordClass: %T", src)
	}
	return nil
}

type NullWordClass struct {
	WordClass WordClass `json:"word_class"`
	Valid     bool      `json:"valid"` // Valid is true if WordClass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWordClass) Scan(value interface{}) error {
	if value == nil {
		ns.WordClass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WordClass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWordClass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WordClass), nil
}

type WordSource string

const (
	WordSourceSeeded      WordSource = "seeded"
	WordSourceContributed WordSource = "contributed"
	WordSourceAiGenerated WordSource = "ai_generated"
)

func (e *WordSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WordSource(s)
	case string:
		*e = WordSource(s)
	default:
		return fmt.Errorf("unsupported scan type for WordSource: %T", src)
	}
	return nil
}

type NullWordSource struct {
	WordSource WordSource `json:"word_source"`
	Valid      bool       `json:"valid"` // Valid is true if WordSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWordSource) Scan(value interface{}) error {
	if value == nil {
		ns.WordSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WordSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWordSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WordSource), nil
}

type WordStatus string

const (
	WordStatusActive     WordStatus = "active"
	WordStatusDeprecated WordStatus = "deprecated"
)

func (e *WordStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WordStatus(s)
	case string:
		*e = WordStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WordStatus: %T", src)
	}
	return nil
}

type NullWordStatus struct {
	WordStatus WordStatus `json:"word_status"`
	Valid      bool       `json:"valid"` // Valid is true if WordStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWordStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WordStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WordStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWordStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WordStatus), nil
}

type Definition struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	WordID    uuid.UUID  `db:"word_id" json:"word_id"`
	Meaning   string     `db:"meaning" json:"meaning"`
	SortOrder int16      `db:"sort_order" json:"sort_order"`
	Source    WordSource `db:"source" json:"source"`
	Upvotes   int32      `db:"upvotes" json:"upvotes"`
	Downvotes int32      `db:"downvotes" json:"downvotes"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt time.Time  `db:"updated_at" json:"updated_at"`
}

type Example struct {
	ID                    uuid.UUID  `db:"id" json:"id"`
	WordID                uuid.UUID  `db:"word_id" json:"word_id"`
	BanjarSentence        string     `db:"banjar_sentence" json:"banjar_sentence"`
	IndonesianTranslation string     `db:"indonesian_translation" json:"indonesian_translation"`
	Source                WordSource `db:"source" json:"source"`
	CreatedAt             time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time  `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID              uuid.UUID    `db:"id" json:"id"`
	Name            string       `db:"name" json:"name"`
	Email           string       `db:"email" json:"email"`
	PasswordHash    string       `db:"password_hash" json:"password_hash"`
	Role            UserRole     `db:"role" json:"role"`
	IsActive        bool         `db:"is_active" json:"is_active"`
	EmailVerifiedAt sql.NullTime `db:"email_verified_at" json:"email_verified_at"`
	CreatedAt       time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time    `db:"updated_at" json:"updated_at"`
}

type Word struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	Banjar            string         `db:"banjar" json:"banjar"`
	BanjarSyllabified sql.NullString `db:"banjar_syllabified" json:"banjar_syllabified"`
	Dialect           Dialect        `db:"dialect" json:"dialect"`
	WordClass         WordClass      `db:"word_class" json:"word_class"`
	HomonymNumber     int16          `db:"homonym_number" json:"homonym_number"`
	IsRoot            bool           `db:"is_root" json:"is_root"`
	RootWordID        uuid.NullUUID  `db:"root_word_id" json:"root_word_id"`
	Status            WordStatus     `db:"status" json:"status"`
	Source            WordSource     `db:"source" json:"source"`
	SourceReference   sql.NullString `db:"source_reference" json:"source_reference"`
	CreatedBy         uuid.NullUUID  `db:"created_by" json:"created_by"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
	DeletedAt         sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type WordRelation struct {
	WordID        uuid.UUID `db:"word_id" json:"word_id"`
	RelatedWordID uuid.UUID `db:"related_word_id" json:"related_word_id"`
}
