// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: words.sql

package sqlcdictionary

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countSearchWords = `-- name: CountSearchWords :one
SELECT COUNT(DISTINCT w.id)::int FROM words w
LEFT JOIN definitions d ON d.word_id = w.id
WHERE w.deleted_at IS NULL
  AND (
        to_tsvector('simple', w.banjar)  @@ plainto_tsquery('simple', $1::text)
     OR to_tsvector('simple', d.meaning) @@ plainto_tsquery('simple', $1::text)
     OR w.banjar ILIKE '%' || $1::text || '%'
  )
  AND ($2::text = '' OR w.word_class::text = $2::text)
  AND ($3::text = '' OR w.is_root = ($3::text = 'true'))
  AND ($4::text = '' OR w.source::text = $4::text)
  AND ($5::text = '' OR w.status::text = $5::text)
`

type CountSearchWordsParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
	Column3 string `db:"column_3" json:"column_3"`
	Column4 string `db:"column_4" json:"column_4"`
	Column5 string `db:"column_5" json:"column_5"`
}

func (q *Queries) CountSearchWords(ctx context.Context, arg CountSearchWordsParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countSearchWords,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countWords = `-- name: CountWords :one
SELECT COUNT(*)::int FROM words
WHERE deleted_at IS NULL
  AND ($1::text = '' OR word_class::text = $1::text)
  AND ($2::text = '' OR is_root = ($2::text = 'true'))
  AND ($3::text = '' OR source::text = $3::text)
  AND ($4::text = '' OR status::text = $4::text)
`

type CountWordsParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
	Column3 string `db:"column_3" json:"column_3"`
	Column4 string `db:"column_4" json:"column_4"`
}

func (q *Queries) CountWords(ctx context.Context, arg CountWordsParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countWords,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createWord = `-- name: CreateWord :one
INSERT INTO words (
    id, banjar, banjar_syllabified, dialect, word_class,
    homonym_number, is_root, root_word_id,
    status, source, source_reference, created_by,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, banjar, banjar_syllabified, dialect, word_class, homonym_number, is_root, root_word_id, status, source, source_reference, created_by, created_at, updated_at, deleted_at
`

type CreateWordParams struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	Banjar            string         `db:"banjar" json:"banjar"`
	BanjarSyllabified sql.NullString `db:"banjar_syllabified" json:"banjar_syllabified"`
	Dialect           Dialect        `db:"dialect" json:"dialect"`
	WordClass         WordClass      `db:"word_class" json:"word_class"`
	HomonymNumber     int16          `db:"homonym_number" json:"homonym_number"`
	IsRoot            bool           `db:"is_root" json:"is_root"`
	RootWordID        uuid.NullUUID  `db:"root_word_id" json:"root_word_id"`
	Status            WordStatus     `db:"status" json:"status"`
	Source            WordSource     `db:"source" json:"source"`
	SourceReference   sql.NullString `db:"source_reference" json:"source_reference"`
	CreatedBy         uuid.NullUUID  `db:"created_by" json:"created_by"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateWord(ctx context.Context, arg CreateWordParams) (Word, error) {
	row := q.db.QueryRowContext(ctx, createWord,
		arg.ID,
		arg.Banjar,
		arg.BanjarSyllabified,
		arg.Dialect,
		arg.WordClass,
		arg.HomonymNumber,
		arg.IsRoot,
		arg.RootWordID,
		arg.Status,
		arg.Source,
		arg.SourceReference,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Banjar,
		&i.BanjarSyllabified,
		&i.Dialect,
		&i.WordClass,
		&i.HomonymNumber,
		&i.IsRoot,
		&i.RootWordID,
		&i.Status,
		&i.Source,
		&i.SourceReference,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWordByID = `-- name: GetWordByID :one
SELECT id, banjar, banjar_syllabified, dialect, word_class, homonym_number, is_root, root_word_id, status, source, source_reference, created_by, created_at, updated_at, deleted_at FROM words
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetWordByID(ctx context.Context, id uuid.UUID) (Word, error) {
	row := q.db.QueryRowContext(ctx, getWordByID, id)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Banjar,
		&i.BanjarSyllabified,
		&i.Dialect,
		&i.WordClass,
		&i.HomonymNumber,
		&i.IsRoot,
		&i.RootWordID,
		&i.Status,
		&i.Source,
		&i.SourceReference,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWordByIDIncludeDeleted = `-- name: GetWordByIDIncludeDeleted :one
SELECT id, banjar, banjar_syllabified, dialect, word_class, homonym_number, is_root, root_word_id, status, source, source_reference, created_by, created_at, updated_at, deleted_at FROM words
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetWordByIDIncludeDeleted(ctx context.Context, id uuid.UUID) (Word, error) {
	row := q.db.QueryRowContext(ctx, getWordByIDIncludeDeleted, id)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Banjar,
		&i.BanjarSyllabified,
		&i.Dialect,
		&i.WordClass,
		&i.HomonymNumber,
		&i.IsRoot,
		&i.RootWordID,
		&i.Status,
		&i.Source,
		&i.SourceReference,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWords = `-- name: ListWords :many
SELECT id, banjar, banjar_syllabified, dialect, word_class, homonym_number, is_root, root_word_id, status, source, source_reference, created_by, created_at, updated_at, deleted_at FROM words
WHERE deleted_at IS NULL
  AND ($1::text = '' OR word_class::text = $1::text)
  AND ($2::text = '' OR is_root = ($2::text = 'true'))
  AND ($3::text = '' OR source::text = $3::text)
  AND ($4::text = '' OR status::text = $4::text)
ORDER BY
    CASE WHEN $5::text = 'recently_added' THEN EXTRACT(EPOCH FROM created_at) END DESC NULLS LAST,
    banjar ASC
LIMIT $6 OFFSET $7
`

type ListWordsParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
	Column3 string `db:"column_3" json:"column_3"`
	Column4 string `db:"column_4" json:"column_4"`
	Column5 string `db:"column_5" json:"column_5"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

// ListWords: $1=word_class filter (” = no filter), $2=is_root filter (” | 'true' | 'false'),
//
//	$3=source filter, $4=status filter, $5=sort ('recently_added' | else alphabetical),
//	$6=limit, $7=offset
func (q *Queries) ListWords(ctx context.Context, arg ListWordsParams) ([]Word, error) {
	rows, err := q.db.QueryContext(ctx, listWords,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Word{}
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.ID,
			&i.Banjar,
			&i.BanjarSyllabified,
			&i.Dialect,
			&i.WordClass,
			&i.HomonymNumber,
			&i.IsRoot,
			&i.RootWordID,
			&i.Status,
			&i.Source,
			&i.SourceReference,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchWords = `-- name: SearchWords :many
SELECT DISTINCT w.id, w.banjar, w.banjar_syllabified, w.dialect, w.word_class, w.homonym_number, w.is_root, w.root_word_id, w.status, w.source, w.source_reference, w.created_by, w.created_at, w.updated_at, w.deleted_at FROM words w
LEFT JOIN definitions d ON d.word_id = w.id
WHERE w.deleted_at IS NULL
  AND (
        to_tsvector('simple', w.banjar)  @@ plainto_tsquery('simple', $1::text)
     OR to_tsvector('simple', d.meaning) @@ plainto_tsquery('simple', $1::text)
     OR w.banjar ILIKE '%' || $1::text || '%'
  )
  AND ($2::text = '' OR w.word_class::text = $2::text)
  AND ($3::text = '' OR w.is_root = ($3::text = 'true'))
  AND ($4::text = '' OR w.source::text = $4::text)
  AND ($5::text = '' OR w.status::text = $5::text)
ORDER BY w.banjar ASC
LIMIT $6 OFFSET $7
`

type SearchWordsParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
	Column3 string `db:"column_3" json:"column_3"`
	Column4 string `db:"column_4" json:"column_4"`
	Column5 string `db:"column_5" json:"column_5"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

func (q *Queries) SearchWords(ctx context.Context, arg SearchWordsParams) ([]Word, error) {
	rows, err := q.db.QueryContext(ctx, searchWords,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Word{}
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.ID,
			&i.Banjar,
			&i.BanjarSyllabified,
			&i.Dialect,
			&i.WordClass,
			&i.HomonymNumber,
			&i.IsRoot,
			&i.RootWordID,
			&i.Status,
			&i.Source,
			&i.SourceReference,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWord = `-- name: SoftDeleteWord :exec
UPDATE words
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWord(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteWord, id)
	return err
}

const updateWord = `-- name: UpdateWord :one
UPDATE words
SET banjar              = $2,
    banjar_syllabified  = $3,
    word_class          = $4,
    homonym_number      = $5,
    is_root             = $6,
    root_word_id        = $7,
    status              = $8,
    source              = $9,
    source_reference    = $10,
    updated_at          = $11
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, banjar, banjar_syllabified, dialect, word_class, homonym_number, is_root, root_word_id, status, source, source_reference, created_by, created_at, updated_at, deleted_at
`

type UpdateWordParams struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	Banjar            string         `db:"banjar" json:"banjar"`
	BanjarSyllabified sql.NullString `db:"banjar_syllabified" json:"banjar_syllabified"`
	WordClass         WordClass      `db:"word_class" json:"word_class"`
	HomonymNumber     int16          `db:"homonym_number" json:"homonym_number"`
	IsRoot            bool           `db:"is_root" json:"is_root"`
	RootWordID        uuid.NullUUID  `db:"root_word_id" json:"root_word_id"`
	Status            WordStatus     `db:"status" json:"status"`
	Source            WordSource     `db:"source" json:"source"`
	SourceReference   sql.NullString `db:"source_reference" json:"source_reference"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateWord(ctx context.Context, arg UpdateWordParams) (Word, error) {
	row := q.db.QueryRowContext(ctx, updateWord,
		arg.ID,
		arg.Banjar,
		arg.BanjarSyllabified,
		arg.WordClass,
		arg.HomonymNumber,
		arg.IsRoot,
		arg.RootWordID,
		arg.Status,
		arg.Source,
		arg.SourceReference,
		arg.UpdatedAt,
	)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Banjar,
		&i.BanjarSyllabified,
		&i.Dialect,
		&i.WordClass,
		&i.HomonymNumber,
		&i.IsRoot,
		&i.RootWordID,
		&i.Status,
		&i.Source,
		&i.SourceReference,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertWord = `-- name: UpsertWord :one
INSERT INTO words (
    id, banjar, banjar_syllabified, dialect, word_class,
    homonym_number, is_root, root_word_id,
    status, source, source_reference, created_by,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (banjar, dialect, homonym_number, is_root, root_word_id) DO UPDATE
SET word_class       = EXCLUDED.word_class,
    source_reference = EXCLUDED.source_reference,
    updated_at       = EXCLUDED.updated_at
RETURNING id, banjar, banjar_syllabified, dialect, word_class, homonym_number, is_root, root_word_id, status, source, source_reference, created_by, created_at, updated_at, deleted_at
`

type UpsertWordParams struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	Banjar            string         `db:"banjar" json:"banjar"`
	BanjarSyllabified sql.NullString `db:"banjar_syllabified" json:"banjar_syllabified"`
	Dialect           Dialect        `db:"dialect" json:"dialect"`
	WordClass         WordClass      `db:"word_class" json:"word_class"`
	HomonymNumber     int16          `db:"homonym_number" json:"homonym_number"`
	IsRoot            bool           `db:"is_root" json:"is_root"`
	RootWordID        uuid.NullUUID  `db:"root_word_id" json:"root_word_id"`
	Status            WordStatus     `db:"status" json:"status"`
	Source            WordSource     `db:"source" json:"source"`
	SourceReference   sql.NullString `db:"source_reference" json:"source_reference"`
	CreatedBy         uuid.NullUUID  `db:"created_by" json:"created_by"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertWord(ctx context.Context, arg UpsertWordParams) (Word, error) {
	row := q.db.QueryRowContext(ctx, upsertWord,
		arg.ID,
		arg.Banjar,
		arg.BanjarSyllabified,
		arg.Dialect,
		arg.WordClass,
		arg.HomonymNumber,
		arg.IsRoot,
		arg.RootWordID,
		arg.Status,
		arg.Source,
		arg.SourceReference,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Banjar,
		&i.BanjarSyllabified,
		&i.Dialect,
		&i.WordClass,
		&i.HomonymNumber,
		&i.IsRoot,
		&i.RootWordID,
		&i.Status,
		&i.Source,
		&i.SourceReference,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
